steps:
  # Step 1 – Normalise keys and save result
  - name: 'python:3.9-slim'
    id: Normalize
    entrypoint: bash
    args:
      - -c
      - |
        pip install pyyaml
        python normalize_keys.py function_config.yaml \
          > /workspace/normalized_config.json

  # Step 2 – Validate the normalised config
  - name: 'python:3.9-slim'
    id: Validate
    entrypoint: bash
    args:
      - -c
      - |
        pip install pyyaml
        python validate_config.py /workspace/normalized_config.json

  # Step 3 – Deploy the Cloud Function (runs only if validation passed)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy-Function
    args:
      - functions
      - deploy
      - "demo-http-function-${SHORT_SHA}"     # from config
      - "--region=us-central1"
      - "--entry-point=helloHttp"
      - "--runtime=nodejs18"
      - "--trigger-http"
      - "--no-allow-unauthenticated"
      - "--gen2"
      - "--build-service-account=YOUR_BUILD_SERVICE_ACCOUNT_EMAIL"
      - "--service-account=YOUR_RUNTIME_SERVICE_ACCOUNT_EMAIL"
      - "--set-env-vars=demoEnvVar=ValueFromConfig"
      - "--source=."

options:
  logging: CLOUD_LOGGING_ONLY
